name: Build Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild CredentialManagerViewer.sln /t:Restore /p:Configuration=release

    - name: Build the application
      run: msbuild CredentialManagerViewer.sln /p:Configuration=release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Binary
        path: CredentialManagerViewer\bin\Release\CredentialManagerViewer.exe
